# Generated by Django 5.0.4 on 2024-11-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adopt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=21)),
                ('category', models.CharField(max_length=5)),
                ('breed', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('color', models.CharField(max_length=25)),
                ('age', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
                ('vaccinated_date', models.DateField()),
                ('health_issue', models.CharField(max_length=100)),
                ('behaviour_people', models.CharField(max_length=14)),
                ('behaviour_animals', models.CharField(max_length=14)),
                ('training', models.CharField(max_length=45)),
                ('fav_activity', models.CharField(max_length=70)),
                ('energy_level', models.CharField(max_length=14)),
                ('prev_owner', models.CharField(max_length=1)),
                ('pet_pic', models.BinaryField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Adopt_Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested_username', models.CharField(max_length=20)),
                ('interested_id', models.IntegerField()),
                ('interested_owner', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Found',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=5)),
                ('breed', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=25)),
                ('pet_name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('date_time', models.DateField()),
                ('pet_pic', models.BinaryField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Found_found',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifound_username', models.CharField(max_length=20)),
                ('ifound_id', models.IntegerField()),
                ('posted_owner', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=5)),
                ('breed', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=25)),
                ('pet_name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('date_time', models.DateField()),
                ('pet_pic', models.BinaryField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Lost_found',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_username', models.CharField(max_length=20)),
                ('found_id', models.IntegerField()),
                ('post_owner', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_Det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=70)),
                ('age', models.CharField(max_length=6)),
                ('prof_img', models.BinaryField(default=None)),
            ],
        ),
        migrations.AddConstraint(
            model_name='adopt_interest',
            constraint=models.UniqueConstraint(fields=('interested_username', 'interested_id', 'interested_owner'), name='unique_interest'),
        ),
        migrations.AddConstraint(
            model_name='found_found',
            constraint=models.UniqueConstraint(fields=('ifound_username', 'ifound_id', 'posted_owner'), name='unique_found'),
        ),
        migrations.AddConstraint(
            model_name='lost_found',
            constraint=models.UniqueConstraint(fields=('found_username', 'found_id', 'post_owner'), name='unique_lost_found'),
        ),
    ]
