# Generated by Django 5.0.4 on 2024-11-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furever_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='forum_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_username', models.CharField(max_length=20)),
                ('comment_date', models.DateTimeField()),
                ('comment_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='forum_posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_username', models.CharField(max_length=20)),
                ('post_date', models.DateTimeField()),
                ('post_title', models.CharField(max_length=55)),
                ('post_description', models.TextField()),
            ],
        ),
    ]
